CREATE TABLE public.downloaded_data (
    raw_file_name text NOT NULL,
    title text,
    speaker_name text NOT NULL,
    language text,
    type text,
    source text NOT NULL,
    utterances_files_list text,
    source_url text,
    speaker_gender text,
    source_website text,
    experiment_name text,
    mother_tongue text,
    age_group text,
    recorded_state text,
    recorded_district text,
    recorded_place text,
    recorded_date text,
    purpose text,
    duration double precision,
    num_of_speakers integer,
    experiment_use boolean,
    load_datetime timestamp without time zone DEFAULT CURRENT_TIMESTAMP(2),
    has_other_audio_signature boolean,
    audio_id text,
    cleaned_duration text,
    staged_for_snr boolean DEFAULT false NOT NULL
);
