COMMON_CONFIG_NAME = 'common'
COMMON_GCS_CONFIG_NAME = 'gcs_config'
COMMON_GCS_BUCKET_CONFIG = 'master_bucket'
CONFIG_NAME = "data_marker_config"
FILTER_CRITERIA = "filter"
FILTER_SPEC = 'filter_spec'
LANDING_BASE_PATH = "landing_directory_path"
SOURCE_BASE_PATH = "source_directory_path"
FILE_MODE = "file_mode"
FILE_PATH = "file_path"
DATA_SET = "data_set"
FILE_COLUMN_LIST = ["speaker_id", "clipped_utterance_file_name", "clipped_utterance_duration", "audio_id", "snr"]
